version: '3'
services:
  db:
    image: postgres:9.6
    container_name: 'local_postgres'
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=docker
      - TZ=GMT
    volumes:
      - './data/postgres:/var/lib/postgresql/data'
    ports:
      - 5432:5432
